New resource `outlook_category`
magodo/terraform-provider-outlook pull request #6
Opened 2020-07-09 03:33 UTC by ArcturusZhang

2020-07-09 05:30 UTC, ArcturusZhang commented
Please hold on merging. I did not get time to run the acc tests yet

2020-07-17 09:34 UTC, ArcturusZhang commented
@magodo Test has passed
```
=== RUN   TestAccOutlookCategory_basic
--- PASS: TestAccOutlookCategory_basic (5.63s)
=== RUN   TestAccOutlookCategory_update
--- PASS: TestAccOutlookCategory_update (8.53s)
PASS
ok      github.com/magodo/terraform-provider-outlook/outlook/services   14.203s
```

2020-07-17 12:02 UTC, magodo requested changes
Thanks for this PR!
I have left some additional mostly minor comments that once addressed this should be good to merge 👍

2020-07-17 12:02 UTC, magodo commented on outlook/services/category_resource.go
> +				Required: true,
Shall we make it `Forcenew`?

2020-07-17 12:02 UTC, magodo commented on website/docs/r/category.html.markdown
> +terraform import outlook_message_rule.example <id>
```suggestion
terraform import outlook_category.example <id>
```

2020-07-20 23:41 UTC, ArcturusZhang commented on website/docs/r/category.html.markdown
> +terraform import outlook_message_rule.example <id>
Oops
Done

2020-07-21 03:09 UTC, ArcturusZhang commented on outlook/services/category_resource.go
> +				Required: true,
Done

2020-07-21 03:13 UTC, ArcturusZhang commented
Hi @magodo I have resolved the comments and the conflicts, please have a look.

2020-07-21 05:56 UTC, merged